# https://taskfile.dev

version: '3'

vars:
  PROJECT_NAME: base-app
  CONTAINER_NAME: tailucas/base-app
  DEVICE_NAME: app-device
  LANG: en_ZA.UTF-8
  LANGUAGE: en_ZA
  SYSLOG_ADDRESS: udp://localhost:514