services:
  app:
    env_file: ".env"
    environment:
      - OP_CONNECT_HOST=${OP_CONNECT_HOST:-http://host.docker.internal:8080}
    secrets:
      - op_service_account_token
      - op_connect_token
      - op_vault
    image: "${CONTAINER_NAME}"
    restart: unless-stopped
    stop_grace_period: 45s
    build:
      network: host
      context: .
      args:
        LANG: "${LANG:-en_ZA.UTF-8}"
        LANGUAGE: "${LANGUAGE:-en_ZA}"
    logging:
      driver: "journald"
      options:
        tag: "{{.Name}}"
    tmpfs:
    - /tmp:exec
    hostname: ${DEVICE_NAME:-base-app}
    volumes:
      - ./data:/data
    extra_hosts:
        - "host.docker.internal:host-gateway"
secrets:
    op_service_account_token:
        environment: OP_SERVICE_ACCOUNT_TOKEN
    op_connect_token:
        environment: OP_CONNECT_TOKEN
    op_vault:
        environment: OP_VAULT
