# https://taskfile.dev

version: '3'

includes:
  taskfile: ./app.yml

vars:
  USER_ID: 999
  GROUP_ID: 999

tasks:
  default:
    cmds:
      - task: build
  datadir:
    desc: Create system user and associate with docker group.
    cmds:
      - mkdir -p ./data/
      - sudo chown {{.USER_ID}}:{{.GROUP_ID}} ./data/
      - sudo chmod 755 ./data/
      - sudo chmod g+rws ./data/
      - sudo rm -f ./data/app-std* ./data/cron-std* ./data/supervisor.sock
  java:
    desc: Build Java artifacts in preparation for container build.
    preconditions:
      - java -version
      - javac -version
      - mvn -v
    cmds:
      - mvn package
      - mvn dependency:tree
    generates:
      - target/app-0.1.0.jar
  python:
    desc: Create and initialize Python virtual environment.
    preconditions:
      - uv -V
    cmds:
      - uv python install
      - uv sync
    generates:
      - .venv
  create-dot-env:
    deps: [python]
    desc: Write project .env
    cmds:
      - ./dot_env_setup.sh {{.PROJECT_NAME}}
    preconditions:
      - uv -V
      - jq -V
      - tr --version
      - sed --version
    generates:
      - .env
  push:
    deps: [build]
    desc: Push built image to Docker Hub
    preconditions:
      - docker compose images
    cmds:
      - docker compose push
  build:
    deps: [create-dot-env, java, python]
    desc: Clean up volume directory and build container image.
    preconditions:
      - docker -v
    cmds:
      - docker compose --env-file .env build --progress plain
  run:
    deps: [build, datadir]
    desc: Run docker container
    preconditions:
      - docker -v
      - test -f docker-compose.yml
      - docker ps | grep 1password
      - test -d ./data/
    cmds:
      - docker compose up --remove-orphans
  rund:
    deps: [build, datadir]
    desc: Run docker container and detach
    preconditions:
      - docker -v
      - test -f docker-compose.yml
      - docker ps | grep 1password
      - test -d ./data/
    cmds:
      - docker compose up -d --remove-orphans
